  yaml
    name: CI/CD Pipeline

    on:
      push:
        branches:
          - master
      pull_request:
        branches:
          - master

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
        - name: Install dependencies
          run: composer install
        - name: Run tests
          run: vendor/bin/phpunit
      deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Deploy to server
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            rsync -r --delete-after ./ user@server:/path/to/deploy
